name:                chip8
version:             0.1.0.0
description:         Chip8 interpreter in Haskell
license:             BSD3
author:              Nick Chapman
maintainer:          nic@amadido.co.uk
github:              Nick-Chapman/chip8.git

extra-source-files:
- README.md

dependencies:
- ansi-terminal
- array
- async
- base >= 4.7 && < 5
- bytestring
- clock
- containers
- containers
- extra
- gloss
- haskeline
- mtl
- random
- split
- text
- time
- transformers
- word8

default-extensions:
- BangPatterns
- BinaryLiterals
- DataKinds
- DeriveFunctor
- DuplicateRecordFields
- EmptyCase
- FlexibleContexts
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- NondecreasingIndentation
- NumericUnderscores
- QualifiedDo
- RankNTypes
- RecordWildCards #Emulator
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- UndecidableInstances

ghc-options:
- -Werror
- -Wall
- -Wno-name-shadowing

executables:
  chip8.exe:
    main:                Main.hs
    source-dirs:         app
